### ISSUE TITLE
getlos com problemas?

### ISSUE THREAD

**Issue by fredericopissarra** [LucGoncalez/LuckyOS#1]
Ao executar o script, obtenho isso:

Atualizando repositório principal... ./getlos: line 95: From: command not found
[FALHA]

Não foi possível atualizar o repositório principal.
Abortando!

Na linha 95 temos:

if $(git pull 2>&1 > /dev/null) ; then

Onde nenhum repositório ou branch é informado... Isso está certo?

**Comment by LucGoncalez** [comment]
Faz o clone do repositório LuckyOS localmente, depois executa o script dentro do repositório local.
